import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Image from "next/image";
import { FiMail } from "react-icons/fi";
import { IoCallOutline } from "react-icons/io5";
import { GrLocation } from "react-icons/gr";
import { IoMdArrowRoundForward } from "react-icons/io";

// const inter = Inter({ subsets: ["latin"] });

import { Manrope, Plus_Jakarta_Sans} from 'next/font/google'
 
const manrope = Manrope({
  subsets: ['latin'],
  variable: '--font-manrope',
  display: 'swap',
  preload:false
})
 
const plusJakartaSans = Plus_Jakarta_Sans({
  subsets: ['latin'],
  variable: '--font-plusJakartaSans',
  display: 'swap',
  preload:false
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${manrope.variable} ${plusJakartaSans.variable}`}>
      <body >
        <nav className="bg-white  border-gray-200 dark:border-gray-700 px-2 md:h-[85px] h-[65px] shadow">
          <div className="container flex flex-wrap justify-between items-center mx-auto py-3 ">
            <Link href="/" className="flex items-center">
              <span className="flex self-center text-xs font-semibold whitespace-nowrap dark:text-white ">
                <Image
                  src="/united-education-logo 1.png"
                  alt="united-education-logo 1"
                  width={72}
                  height={48}
                  className="p-3"
                />{" "}
              </span>
            </Link>
            <div className="hidden   lg:inline">
              <ul className="flex flex-col mt-4 md:flex-row md:space-x-8 md:mt-0 md:text-sm md:font-medium">
                <li>
                  <Link href="/">
                    <span className="align-baseline flex justify-center gap-2 py-2 pr-4 pl-3 text-gray-700  border-gray-100 hover:bg-gray-50 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 ">
                      <FiMail className="mt-1 text-red-600" />
                      <div className="flex-col">
                        <h1 className="block text-red-600">Email</h1>
                        <span className="font-light">
                          info@united-education.com
                        </span>
                      </div>
                    </span>
                  </Link>
                </li>
                <li>
                  <Link href="/">
                    <span className="align-baseline flex justify-center gap-2 py-2 pr-4 pl-3 text-gray-700  border-gray-100 hover:bg-gray-50 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0">
                      <IoCallOutline className="mt-1 text-red-600" />
                      <div className="flex-col">
                        <h1 className="block text-red-600">call Us</h1>
                        <span className="font-light">+964 7517627727</span>
                      </div>
                    </span>
                  </Link>
                </li>
                <li>
                  <Link href="/">
                    <span className="align-baseline flex justify-center gap-2 py-2 pr-4 pl-3 text-gray-700  border-gray-100 hover:bg-gray-50 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0">
                      <GrLocation className="mt-1 text-red-600" />
                      <div className="flex-col">
                        <h1 className="block text-red-600">Location</h1>
                        <span className="font-light">
                          Erbil,Empire Business Tower,Tower 4,Floor 15, Office
                          NO 1
                        </span>
                      </div>
                    </span>
                  </Link>
                </li>
              </ul>
            </div>
            <div className="flex items-center">
              <button
                type="button"
                className="lg:hidden md:inline-flex items-center p-2 ml-3 text-sm text-gray-500 rounded-lg hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600"
              >
                <span className="sr-only">Open main menu</span>
                {/* Hamburger icon */}
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  fill="none"
                  viewBox="0 0 24 24"
                  stroke="currentColor"
                  stroke-width="2"
                  className="h-6 w-6"
                >
                  <path
                    d="M3 5h18M3 12h18M3 19h18"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                  />
                </svg>
              </button>
            </div>
          </div>
        </nav>

        {children}

        {/* footer */}

        <footer className=" w-full bg-[#022837]">
          <div className="parent container justify-evenly flex flex-col w-full lg:flex-row  md:text-left  text-center  mx-auto p-10 ">
            {/* child 1 */}
            <div className="fchild_1 flex flex-col lg:flex-col md:flex-row  md:justify-between w-full lg:w-72  items-center md:items-start   text-white ">
              <div className="">
                <Image
                  src="/sticky-logo 1.png"
                  alt="united-education-logo 1"
                  width={110}
                  height={60}
                  className="p-3"
                />{" "}
              </div>
              <div className="w-[267px] lg:mt-[30px]">
                <h1 className="text-[18px] font-normal ">
                  Sign up for releases & product updates...
                </h1>
                <form className="w-full max-w-xs">
                  <div className="flex items-center border-b border-[#CFCFCF] py-2">
                    <input
                      className="appearance-none bg-transparent border-none w-full text-[#CFCFCF] mr-3 py-1 px-2 leading-tight focus:outline-none"
                      type="text"
                      placeholder="Enter email Address"
                      aria-label="Full name"
                    />
                    <button
                      className="flex-shrink-0 border-transparent border-4 text-[#CFCFCF] hover:text-[#CFCFCF]-800 text-sm py-1 px-2 rounded"
                      type="button"
                    >
                      <IoMdArrowRoundForward />
                    </button>
                  </div>
                </form>
              </div>
            </div>

            <div className="fchild_2 mt-5 flex flex-col md:flex-row flex-wrap lg:gap-[63px] gap-0  justify-center text-center md:text-left md:justify-around">
              <div className="about">
                <h1 className="text-white">About</h1>
                <ul className="text-[#CFCFCF] lg:text-lg  text-sm">
                  <li>Our Story</li>
                  <li>Treatments Safer</li>
                  <li>Journal</li>
                  <li>Candles</li>
                </ul>
              </div>{" "}
              <div className="about">
                <h1 className="text-white">Company</h1>
                <ul className="text-[#CFCFCF] md:block hidden lg:text-lg text-sm">
                  <li>About</li>
                  <li>Contact</li>
                  <li>Products</li>
                  <li>Privacy</li>
                </ul>
              </div>{" "}
              <div className="about">
                <h1 className="text-white">Help</h1>
                <ul className="text-[#CFCFCF] md:block hidden lg:text-lg text-sm">
                  <li>FAQs</li>
                  <li>Terms of service</li>
                  <li>Cookies</li>
                  <li>Privacy</li>
                </ul>
              </div>{" "}
              <div className="about">
                <h1 className="text-white">SocialMedia</h1>
                <ul className="text-[#CFCFCF] md:block hidden lg:text-lg text-sm">
                  <li>Facebook</li>
                  <li>Instagram</li>
                  <li>Linkedin</li>
                </ul>
              </div>{" "}
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
